theme: jekyll-theme-leap-day
title: |-
  JARVIS: Scalable and Precise Application-Centered Call Graph Generation for Python

markdown: kramdown

# description: Annotation Countsï¼šUnveiling Missing and Spurious Calls for Analyzing Spring Web Applications
math:
    engine: 'mathjax'
    mathjax:
        src: "//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
        config:
            tex2jax:
                inlineMath: [ ['$','$'], ["\\(","\\)"] ]
